In [1]:
!pip install python-dotenv kaggle

Requirement already satisfied: python-dotenv in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.2.2)
Requirement already satisfied: kaggle in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.2.4)
Requirement already satisfied: bleach in /home/codespace/.local/lib/python3.12/site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/python/3.12.1/lib/python3.12/site-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in /home/codespace/.local/lib/python3.12/site-packages (from kaggle) (26.0)
Requirement already satisfied: protobuf in /usr/local/python/3.12.1/lib/python3.12/site-packages (from kaggle) (7.35.1)
Requirement already satisfied: python-dateutil in /home/codespace/.local/lib/python3.12/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/python/3.12.1/lib/python3.12/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /home/codespace/.local/lib/python3.12/site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in /usr/local/python/3.12.1/lib/python3.12/site-packages (from kaggle) (4.70.0)
Requirement already satisfied: urllib3>=1.15.1 in /home/codespace/.local/lib/python3.12/site-packages (from kaggle) (2.6.3)
Requirement already satisfied: webencodings in /home/codespace/.local/lib/python3.12/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/python/3.12.1/lib/python3.12/site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /home/codespace/.local/lib/python3.12/site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /home/codespace/.local/lib/python3.12/site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /home/codespace/.local/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /home/codespace/.local/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/codespace/.local/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /home/codespace/.local/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.9.4)
Requirement already satisfied: typing-extensions>=4.4.0 in /home/codespace/.local/lib/python3.12/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests->kaggle) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests->kaggle) (2026.2.25)

[notice] A new release of pip is available: 26.0.1 -> 26.2
[notice] To update, run: pip install --upgrade pip

In [2]:
from dotenv import load_dotenv
import os

load_dotenv()

HF_TOKEN = os.getenv("HF_TOKEN")
KAGGLE_USERNAME = os.getenv("KAGGLE_USERNAME")
KAGGLE_KEY = os.getenv("KAGGLE_KEY")

In [3]:
import os

os.environ["KAGGLE_USERNAME"] = KAGGLE_USERNAME
os.environ["KAGGLE_KEY"] = KAGGLE_KEY

from kaggle.api.kaggle_api_extended import KaggleApi

api = KaggleApi()
api.authenticate()

print("Kaggle authenticated successfully.")

Kaggle authenticated successfully.

In [4]:
DOWNLOAD_DIR = "../data/raw"

api.dataset_download_files(
    "aealemran/thesis-dataset2",
    path=DOWNLOAD_DIR,
    unzip=True
)

print("Dataset downloaded successfully.")

Dataset URL: https://www.kaggle.com/datasets/aealemran/thesis-dataset2

Dataset downloaded successfully.

In [5]:
from pathlib import Path

RAW_DIR = Path("../data/raw")

for item in RAW_DIR.iterdir():
    print(item)

../data/raw/Thesis_dataset2

In [6]:
for path in RAW_DIR.rglob("*"):
    print(path)

../data/raw/Thesis_dataset2
../data/raw/Thesis_dataset2/DangerousDriving
../data/raw/Thesis_dataset2/Yawn
../data/raw/Thesis_dataset2/Openeye
../data/raw/Thesis_dataset2/Drinking
../data/raw/Thesis_dataset2/SafeDriving
../data/raw/Thesis_dataset2/Distracted
../data/raw/Thesis_dataset2/closed
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-868_jpg.rf.b9f2f685d1add96abf4bdfd4c048f340.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-527_jpg.rf.07cce399daf961f7053fb974622427c5.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-536_jpg.rf.fb126d91ccf81229fed49d2cf109c04d.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-559_jpg.rf.fabf4f552614f877deb084bd4cec9021.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-905_jpg.rf.2a2a6eeab3d1f53c068fb3dcbe5f2e05.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-561_jpg.rf.db2381e40edba8884707338621f693a2.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-670_jpg.rf.08cbbd1fe1b89b0d22709b93688dc907.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-162_jpg.rf.b8e19e1f34b8747b9b926b5bacc8b494.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-637_jpg.rf.d3247ff78069e0aa6af1373c9fe7fad3.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-923_jpg.rf.f2ec8f9f4f965e5dcba9fd9634a5077a.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-198_jpg.rf.e17608e1aa7783e96110e4d166849e58.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s5_ir_face_mp4-0_jpg.rf.c1d65f2c96251718f8f81a53525e1ede.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_4_s2_ir_face_mp4-161_jpg.rf.0365c777d47eee48dc57663180991fb8.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-564_jpg.rf.b4d78f9d8ae07b1de936f58b96e0004f.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-113_jpg.rf.7c2038c5f48ea46cdf84e600bccab832.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-621_jpg.rf.4de78158d7189f82b908799ef6562610.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-307_jpg.rf.922b456ceffe2881da81620e981d9d9c.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-400_jpg.rf.ec87d15eb4b03c7aed1266fd5c45c91f.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-869_jpg.rf.da0c1412622e7c996d3a3368ab93489f.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-623_jpg.rf.3099d15df65dd056ed56bb01c80cf95c.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-572_jpg.rf.a1874230635119dba85cf647bf029400.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-494_jpg.rf.2ad1d87fa9571808f00f75d29a78b3b4.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-524_jpg.rf.4f2aa1f711e3de239dc8c439595d61fe.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-749_jpg.rf.d96e33d8cbe2021ac77b83f5e4434329.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-148_jpg.rf.c9fde3b74c3b54844ad96fa656d22864.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-137_jpg.rf.77e3b7a3eddaf2266cfb066b6ecb5cfe.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-276_jpg.rf.3f206fadcc0b24bcab7c6e9efd4b5cc4.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-180_jpg.rf.b3b97b2affe58c7689032b50aa785779.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-330_jpg.rf.bd1a885b5221989b7509c5c807b699a6.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-32_jpg.rf.11e7b186f7558b37ee244a0c6973233f.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_1_s2_ir_face_mp4-160_jpg.rf.9c9126ed7eea98f08abf1767d059045e.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-341_jpg.rf.1e397fc5cad4149e9abe63969f112b1c.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-99_jpg.rf.0dc156a6b647e82acebd10e190a453f7.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-807_jpg.rf.d0bd175deda8f8e48cdd1cfe12167daf.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-53_jpg.rf.1e77504542a8a7950768dced9dbbc32a.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-74_jpg.rf.6394350c077afc081391bd163a10a0e3.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-165_jpg.rf.553f2b152f2321d4f5b73e4fa29a9b84.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-279_jpg.rf.af9a230eefd7aee0265990923918dee2.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-310_jpg.rf.d913df389b8ffc45c04479094a327159.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-616_jpg.rf.42f367700216909b69fb658afa96abc2.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-569_jpg.rf.6b793c7dd6342d1bb070828b658f9f88.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-599_jpg.rf.061a2a4748f9195b51b6624fcfaa28cf.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-262_jpg.rf.51af8a046fb8a19639e8f338fdc428a5.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_1_s2_ir_face_mp4-264_jpg.rf.f52a6efff64eab541276a86e45cc58e8.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-524_jpg.rf.4e192743cd5dff48176f38fe80d88b47.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-342_jpg.rf.7901846476d61c313ed65df3219b7cc9.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-542_jpg.rf.91eba80370a2a2db900aa2752fca8cc8.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-262_jpg.rf.ac8c46a0e1035b2b21c4d0dfa5c83f2a.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-1000_jpg.rf.35e83517ffd1b023c9fe047c1126bb56.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-60_jpg.rf.e3c7856024d4e8256ec36aeb0a37f010.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_5_s2_ir_face_mp4-333_jpg.rf.14eaf3d6d7102e9714c5276a711a0884.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-380_jpg.rf.4897e29f3a7784c131300b3228ebbff1.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-102_jpg.rf.dbea62e02dcb92e0e9c88fd96934d461.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-70_jpg.rf.8048b56186f709384e9435ce3095ad70.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-58_jpg.rf.f6051f33e6c0292f93c68efcebcf9064.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-61_jpg.rf.043090598971c5a9a66c8c35bfed3126.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-309_jpg.rf.b2cc7f3dc2803b099fc114e785db24da.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-314_jpg.rf.67023a54d4079da5d82a1f0929398c41.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_1_s2_ir_face_mp4-57_jpg.rf.9247731b91eac01d4389ee894c9f779b.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-323_jpg.rf.def35a1ab30c8792a2d4ed2c26a4d66f.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-633_jpg.rf.928b559dd221b9075f6aaf27d9b95fee.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-627_jpg.rf.f9cda5b914ec85e8f36cd786fc239447.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-251_jpg.rf.d90744bcae5a843d09a1cbfc03185397.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-695_jpg.rf.a47e1894a8dbce12a029c9ba7e4230e6.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-676_jpg.rf.d786fb18db23270150fbab92aed47025.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-587_jpg.rf.d32bc385f5f348e58bef7661ba3ff625.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-73_jpg.rf.734219b3f53915aa2403cd04a044a152.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-345_jpg.rf.97075de6586c84b855d9eea0dbd28da0.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-112_jpg.rf.d48035361ef93f046a63f084f57c3a42.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-884_jpg.rf.a25b37334388ae15fd9a443ad81b8786.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-269_jpg.rf.bc51670e4636c584a64aad9f3498ecbc.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-573_jpg.rf.84164871b251c3d96afe5000d7ac40f4.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_5_s2_ir_face_mp4-349_jpg.rf.d0e785797d42f9b0269a5174c5961d3a.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-523_jpg.rf.305386e6fd12a594a460a7d112380c32.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_1_s2_ir_face_mp4-58_jpg.rf.42bf14df8f8b7cf0d2325586365ae742.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-901_jpg.rf.09909d8f94c50b734949965daeee86e7.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-768_jpg.rf.3be44f452e46d208688333beb82b4871.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-118_jpg.rf.1f442285e90491956ac5517df0014bd6.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-785_jpg.rf.e849b81da74dec8c71f425ee80f088f6.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-543_jpg.rf.893a1d27a1efc46d043109ea6af21bf2.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-264_jpg.rf.4074d2831454c156afb8a8c088734276.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_4_s5_ir_face_mp4-0_jpg.rf.6df6e85be7e0db6430b37aad2fa1e2c8.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-700_jpg.rf.dc1f3db301e2076ef58fda9e5c57f7bf.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-508_jpg.rf.15db76dee2ba448163cb668cbea75dd2.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-96_jpg.rf.702bd17d649a30e6fbcfff85748ef00f.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-796_jpg.rf.4ba7c370738fcbc3cb385a3bda20901f.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-683_jpg.rf.c34ce0ec1ac9608b83161ae96f070924.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-114_jpg.rf.2efdeab6dbfbd74228854dd1c7f37191.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-820_jpg.rf.986ecb4dbd054e42b1cfe7ce298f02d4.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-587_jpg.rf.23150f660e7198b7be9f98942f3bd178.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-278_jpg.rf.1469d0621cb0efd708a51ee1a0fa95f1.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_4_s2_ir_face_mp4-371_jpg.rf.ddf80b500ff5874b3cce0b64480faf8e.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-160_jpg.rf.dd02ed9a88d09416bdf9aa28efed8bc1.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-239_jpg.rf.c28e3a96962d631b1db007a919347377.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-355_jpg.rf.104ed3d956bbfc759ca76b3cd090c72b.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-115_jpg.rf.7028f3d672d3df59dc0da6500e89c750.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-320_jpg.rf.e5e667973cf2f6c382240849c84ffe86.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-867_jpg.rf.f800dc9797591e91733aef522fa1a64a.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-197_jpg.rf.c3ffb7d10db2a707106f64a69b94872f.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-741_jpg.rf.90eb1c7717060e4dad386a77e6729838.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-636_jpg.rf.f8db9d286ca46b3402282e9e25582566.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-818_jpg.rf.a487327e56422f02812e71eb1da0dc64.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_4_s2_ir_face_mp4-372_jpg.rf.448fec2e90c845fb001e846cae384df8.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-545_jpg.rf.3f4d654ef9500b8e2decc09d5103389b.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-83_jpg.rf.54813bfde28839bae3ef693befe5d963.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-65_jpg.rf.46d9f046a8adf35d0dd75ff2e819937f.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-675_jpg.rf.c67f56c7127ebf3d02ecb20dfc9f5109.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-49_jpg.rf.de787da8004373f8afb4bfd2db4483c3.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-186_jpg.rf.1e41db1e44e8026d1555fdbc841c825f.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-560_jpg.rf.0c60beece6a8cb31c477035bd39c0093.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-122_jpg.rf.e67c932a50bdfd058fe0f32170d37204.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-832_jpg.rf.221154b217193698bb8da63f2b8c8e4e.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-153_jpg.rf.e1c6164d80dbb576b660f93c76b98829.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-708_jpg.rf.739541b450ecd5eb354cb2a3ce05d93e.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-125_jpg.rf.a6bed4b2973b2fab47b0222c8ca408b0.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-111_jpg.rf.1c51acb0faedbedf8112e0316e48ab19.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-560_jpg.rf.021181722cca74cb10aa63d984498d19.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-757_jpg.rf.f43dcc37e4ee96dce38af17536422d2e.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-575_jpg.rf.17864505c60a93e20755cb872fb8316c.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_1_s2_ir_face_mp4-172_jpg.rf.441fdcb15715add1867db1842873f019.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-414_jpg.rf.4eca34394981f0018985f80fa9be62d5.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-121_jpg.rf.d079b6ca23689c96bc0b7e15dc428ac1.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-887_jpg.rf.022d53461a060677f143c9050a4952f6.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-177_jpg.rf.98d1fca8661241545e9671e2e8b641c6.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-704_jpg.rf.4ddbb55f484de1464d563969f1b4872b.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-314_jpg.rf.5496bcdabfdfd8dd1ae69e3936e1c08b.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-152_jpg.rf.a10703dafadbc3d00ef6cbb178e25831.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-801_jpg.rf.d7e1bcc7a72498fcd1b763c5095a09fe.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-559_jpg.rf.267eb86070cc116823a86ffc3450280e.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-970_jpg.rf.0eba9f9bbb26b64f64ce34c302364138.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-865_jpg.rf.a427b63e30201bd21e668bc160452bb1.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-592_jpg.rf.2627712846066221cd80cccb6242febf.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-557_jpg.rf.5f712171760d75644f76e202d330f068.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-688_jpg.rf.a6fe2c4c474d4c4f60e948ede3adaef6.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-116_jpg.rf.9b9ec2c1d3a3363c4aac50bb01c5cf7b.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-290_jpg.rf.001ab12b658998ffaebbfe234acf1b0a.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_4_s2_ir_face_mp4-285_jpg.rf.014d191bfdb8db5e670ad0e2c664fefa.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-156_jpg.rf.88238dd55d614cb17b0b303ba8c53806.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-475_jpg.rf.a1b89d252d563833b4c3c13eb16aa079.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_3_s2_ir_face_mp4-172_jpg.rf.3a370b93346610abdc1dc468fae889c4.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-350_jpg.rf.23e31189f83cbcf50c1de3dcdbb93bff.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-573_jpg.rf.2e7b3f9d67822fd7c032b78a3f11f392.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-331_jpg.rf.d0dd9c60b797c5a8399425e20bd7cb69.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-573_jpg.rf.492a04eee96ca9cfe30be29b6acfae86.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-211_jpg.rf.a1ae126cdac06f6998e956c8f848ab45.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_4_s2_ir_face_mp4-193_jpg.rf.3952eed49b17633e8cbe9ad488abfbb1.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-629_jpg.rf.d9b0a38505bad4e1d482452ecadf49a2.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_2_s2_ir_face_mp4-214_jpg.rf.eec78b6a0a6d3c35264cbf24645dfe1d.jpg
../data/raw/Thesis_dataset2/DangerousDriving/gA_4_s2_ir_face_mp4-385_jpg.rf.4d7172019e56f28481d427e24a8df6f7.jpg

____________________________ Discovering different datasets__________________________

In [9]:
from pathlib import Path

RAW_DATASET = Path("../data/raw/Thesis_dataset2")

for folder in RAW_DATASET.iterdir():
    if folder.is_dir():
        print("\n", folder.name)
        for f in list(folder.rglob("*"))[:10]:
            print("   ", f)

 DangerousDriving
    ../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-868_jpg.rf.b9f2f685d1add96abf4bdfd4c048f340.jpg
    ../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-527_jpg.rf.07cce399daf961f7053fb974622427c5.jpg
    ../data/raw/Thesis_dataset2/DangerousDriving/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-536_jpg.rf.fb126d91ccf81229fed49d2cf109c04d.jpg
    ../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-559_jpg.rf.fabf4f552614f877deb084bd4cec9021.jpg
    ../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-905_jpg.rf.2a2a6eeab3d1f53c068fb3dcbe5f2e05.jpg
    ../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-561_jpg.rf.db2381e40edba8884707338621f693a2.jpg
    ../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-670_jpg.rf.08cbbd1fe1b89b0d22709b93688dc907.jpg
    ../data/raw/Thesis_dataset2/DangerousDriving/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-162_jpg.rf.b8e19e1f34b8747b9b926b5bacc8b494.jpg
    ../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-637_jpg.rf.d3247ff78069e0aa6af1373c9fe7fad3.jpg
    ../data/raw/Thesis_dataset2/DangerousDriving/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-923_jpg.rf.f2ec8f9f4f965e5dcba9fd9634a5077a.jpg

 Yawn
    ../data/raw/Thesis_dataset2/Yawn/220_jpg.rf.48dc523e8f645ffaf3da611f4f097ec3.jpg
    ../data/raw/Thesis_dataset2/Yawn/gB_10_s5_2019-03-12T10-35-2001-00_ir_face_mp4-85_jpg.rf.0c02e4914353a43cccff4ab73e5fafd3.jpg
    ../data/raw/Thesis_dataset2/Yawn/212_jpg.rf.9c3ec7064c539b74bda97bc8e2571f99.jpg
    ../data/raw/Thesis_dataset2/Yawn/365_jpg.rf.eb7ae967ead8b6889933879c5b17e49c.jpg
    ../data/raw/Thesis_dataset2/Yawn/gB_6_s5_2019-03-13T13-37-1101-00_ir_face_mp4-263_jpg.rf.493b3b0de368551307a8cfa68a7219e0.jpg
    ../data/raw/Thesis_dataset2/Yawn/123_jpg.rf.ef52e52f9ae05be2883d9e5ece2c41a0.jpg
    ../data/raw/Thesis_dataset2/Yawn/gB_7_s5_2019-03-13T13-55-5201-00_ir_face_mp4-46_jpg.rf.7447e7980d7272fd31a281ebe84f9f3d.jpg
    ../data/raw/Thesis_dataset2/Yawn/660_jpg.rf.b7fd0fe978e253f5e8264cb9fc528b22.jpg
    ../data/raw/Thesis_dataset2/Yawn/24_jpg.rf.d558130141186b06952826b5d0c4d300.jpg
    ../data/raw/Thesis_dataset2/Yawn/89_jpg.rf.10756685e728e404079029ee6e7452e5.jpg

 Openeye
    ../data/raw/Thesis_dataset2/Openeye/kaggle_flickrfaceshq-dataset-ffhq_02262_eye_RIGHT.png
    ../data/raw/Thesis_dataset2/Openeye/kaggle_flickrfaceshq-dataset-ffhq_48248_eye_RIGHT.png
    ../data/raw/Thesis_dataset2/Openeye/kaggle_flickrfaceshq-dataset-ffhq_04238_eye_LEFT.png
    ../data/raw/Thesis_dataset2/Openeye/kaggle_flickrfaceshq-dataset-ffhq_03110_eye_RIGHT.png
    ../data/raw/Thesis_dataset2/Openeye/kaggle_flickrfaceshq-dataset-ffhq_02667_eye_RIGHT.png
    ../data/raw/Thesis_dataset2/Openeye/kaggle_flickrfaceshq-dataset-ffhq_05465_eye_RIGHT.png
    ../data/raw/Thesis_dataset2/Openeye/kaggle_flickrfaceshq-dataset-ffhq_04171_eye_RIGHT.png
    ../data/raw/Thesis_dataset2/Openeye/kaggle_flickrfaceshq-dataset-ffhq_04624_eye_LEFT.png
    ../data/raw/Thesis_dataset2/Openeye/kaggle_flickrfaceshq-dataset-ffhq_06797_eye_LEFT.png
    ../data/raw/Thesis_dataset2/Openeye/kaggle_flickrfaceshq-dataset-ffhq_07390_eye_LEFT.png

 Drinking
    ../data/raw/Thesis_dataset2/Drinking/img_33850_jpg.rf.b5e996f9b714188e1ff1639a7027105b.jpg
    ../data/raw/Thesis_dataset2/Drinking/img_28125_jpg.rf.eadcd01029b15589636fa55175403ca8.jpg
    ../data/raw/Thesis_dataset2/Drinking/img_43063_jpg.rf.35a76bac96a506f07e39c73bfc0ced34.jpg
    ../data/raw/Thesis_dataset2/Drinking/img_57868_jpg.rf.41e8ac138a7e51b9c084d58c827f37ba.jpg
    ../data/raw/Thesis_dataset2/Drinking/img_50625_jpg.rf.32dc819ee7a645ee715190d2d2cc7e72.jpg
    ../data/raw/Thesis_dataset2/Drinking/img_32973_jpg.rf.37c1d2d8cff0f40f8a052e9ee054ca02.jpg
    ../data/raw/Thesis_dataset2/Drinking/img_91540_jpg.rf.cf011592e7a20ce811b62153a24d8b18.jpg
    ../data/raw/Thesis_dataset2/Drinking/img_11987_jpg.rf.67f24f1d7f46bfcc8756c87fb5692722.jpg
    ../data/raw/Thesis_dataset2/Drinking/img_3850_jpg.rf.7d46b0ad9cddf8d4123ef35d934fb605.jpg
    ../data/raw/Thesis_dataset2/Drinking/img_24829_jpg.rf.7a4a24bb144bbc74c736b38d70575ab5.jpg

 SafeDriving
    ../data/raw/Thesis_dataset2/SafeDriving/img_59709.jpg
    ../data/raw/Thesis_dataset2/SafeDriving/img_58289.jpg
    ../data/raw/Thesis_dataset2/SafeDriving/img_62643.jpg
    ../data/raw/Thesis_dataset2/SafeDriving/img_51330.jpg
    ../data/raw/Thesis_dataset2/SafeDriving/img_71418.jpg
    ../data/raw/Thesis_dataset2/SafeDriving/img_64755.jpg
    ../data/raw/Thesis_dataset2/SafeDriving/img_48729.jpg
    ../data/raw/Thesis_dataset2/SafeDriving/img_37346.jpg
    ../data/raw/Thesis_dataset2/SafeDriving/img_9006.jpg
    ../data/raw/Thesis_dataset2/SafeDriving/img_20632.jpg

 Distracted
    ../data/raw/Thesis_dataset2/Distracted/gB_7_s2_2019-03-11T14-12-25-01-00_ir_face_mp4-472_jpg.rf.84caa26a7bd9eb624fede8ba13496e4b.jpg
    ../data/raw/Thesis_dataset2/Distracted/gB_10_s2_2019-03-11T15-15-21-01-00_ir_face_mp4-84_jpg.rf.a42a40819f9ae8480d632587679f3de3.jpg
    ../data/raw/Thesis_dataset2/Distracted/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-478_jpg.rf.0a11d88884cfe1df2772e9588801eaac.jpg
    ../data/raw/Thesis_dataset2/Distracted/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-895_jpg.rf.97ac37ae0a7d7cad46fa5da20c6f48b7.jpg
    ../data/raw/Thesis_dataset2/Distracted/gA_4_s2_ir_face_mp4-324_jpg.rf.2c72251f77c260e4bb5383fa7074f83d.jpg
    ../data/raw/Thesis_dataset2/Distracted/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-260_jpg.rf.5935f5b95937de82c05ec4d1a25ea37b.jpg
    ../data/raw/Thesis_dataset2/Distracted/gB_6_s2_2019-03-11T13-46-14-01-00_ir_face_mp4-691_jpg.rf.ce34cd7a2b8d146f29ca1b1be944d536.jpg
    ../data/raw/Thesis_dataset2/Distracted/gB_9_s2_2019-03-07T16-21-20-01-00_ir_face_mp4-401_jpg.rf.40f1105694d5210f22afd9c8f6d66568.jpg
    ../data/raw/Thesis_dataset2/Distracted/gB_10_s1_2019-03-11T15-24-54-01-00_ir_face_mp4-79_jpg.rf.0aba766498b98aa97d718d57b9d15612.jpg
    ../data/raw/Thesis_dataset2/Distracted/gB_8_s2_2019-03-11T14-38-44-01-00_ir_face_mp4-636_jpg.rf.57d8bb25bc56817447aba0241e9c19d6.jpg

 closed
    ../data/raw/Thesis_dataset2/closed/_636.png
    ../data/raw/Thesis_dataset2/closed/_402.png
    ../data/raw/Thesis_dataset2/closed/s0001_00833_0_0_0_0_0_01.png
    ../data/raw/Thesis_dataset2/closed/s0001_01564_0_1_0_0_0_01.png
    ../data/raw/Thesis_dataset2/closed/s0002_00148_0_0_0_0_0_01.png
    ../data/raw/Thesis_dataset2/closed/s0001_01641_0_1_0_0_0_01.png
    ../data/raw/Thesis_dataset2/closed/_609.png
    ../data/raw/Thesis_dataset2/closed/s0002_00110_0_0_0_0_0_01.png
    ../data/raw/Thesis_dataset2/closed/s0001_01539_0_1_0_0_0_01.png
    ../data/raw/Thesis_dataset2/closed/_196.png

In [11]:
from pathlib import Path
import pandas as pd

IMAGE_EXTS = {".png", ".jpg", ".jpeg"}

summary = []

for cls in classes:

    folder = RAW_DATASET / cls

    images = [
        f for f in folder.rglob("*")
        if f.suffix.lower() in IMAGE_EXTS
    ]

    summary.append({
        "class": cls,
        "images": len(images)
    })

summary = pd.DataFrame(summary)

summary

              class  images
0  DangerousDriving    2478
1        Distracted    1672
2          Drinking    2099
3           Openeye    2000
4       SafeDriving    2203
5              Yawn    2731
6            closed    1233

In [13]:
from pathlib import Path
import shutil
import random
import pandas as pd

random.seed(42)

# ----------------------------
# Paths
# ----------------------------
RAW_DATASET = Path("../data/raw/Thesis_dataset2")

SAMPLE_DIR = Path("../data/samples")

SAMPLE_DIR.mkdir(parents=True, exist_ok=True)

# ----------------------------
# Parameters
# ----------------------------
SAMPLES_PER_CLASS = 200   # Change to 300 or 500 later if required
RANDOM_SEED = 42

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg"}

metadata = []
sampling_summary = []

# ----------------------------
# Sampling
# ----------------------------
for cls in sorted(classes):

    source_folder = RAW_DATASET / cls
    target_folder = SAMPLE_DIR / cls

    target_folder.mkdir(parents=True, exist_ok=True)

    images = [
        img for img in source_folder.rglob("*")
        if img.suffix.lower() in IMAGE_EXTENSIONS
    ]

    original_count = len(images)

    sample_size = min(SAMPLES_PER_CLASS, original_count)

    sampled_images = random.sample(images, sample_size)

    for img in sampled_images:

        shutil.copy2(
            img,
            target_folder / img.name
        )

        metadata.append({

            "file_name": img.name,
            "label": cls,
            "dataset": "Thesis_dataset2",
            "original_path": str(img)

        })

    sampling_summary.append({

        "class": cls,
        "original_images": original_count,
        "sampled_images": sample_size,
        "sampling_percentage": round(
            sample_size / original_count * 100,
            2
        )

    })

# ----------------------------
# Save Metadata
# ----------------------------
metadata = pd.DataFrame(metadata)

sampling_summary = pd.DataFrame(sampling_summary)

metadata.to_csv(
    SAMPLE_DIR / "metadata.csv",
    index=False
)

sampling_summary.to_csv(
    SAMPLE_DIR / "sampling_summary.csv",
    index=False
)

print("✅ Sampling Completed")
print(f"Total Sampled Images : {len(metadata)}")

display(sampling_summary)

✅ Sampling Completed
Total Sampled Images : 1400

              class  original_images  sampled_images  sampling_percentage
0  DangerousDriving             2478             200                 8.07
1        Distracted             1672             200                11.96
2          Drinking             2099             200                 9.53
3           Openeye             2000             200                10.00
4       SafeDriving             2203             200                 9.08
5              Yawn             2731             200                 7.32
6            closed             1233             200                16.22